import { RouteMeta, RouteStop } from "@/types";

export const routeMeta: RouteMeta = {
  title: "Ámsterdam en bici",
  tagline: "Un día, doce paradas, la ciudad entera desde el sillín.",
  totalKm: 9,
  totalDurationLabel: "8–9 h con paradas, empezando sobre las 9:00",
  difficulty: "Fácil",
};

export const stops: RouteStop[] = [
  {
    id: "centraal",
    order: 1,
    name: "Amsterdam Centraal",
    dayPart: "mañana",
    summary: "Punto de partida: recoge tu bici y coge el ritmo de la ciudad.",
    whatToSee:
      "La fachada del siglo XIX de la estación y el ajetreo del carril bici más denso de la ciudad, justo a la salida.",
    minutesHere: 10,
    tip: "Sal despacio: aquí confluyen tranvías, peatones y cientos de bicis a la vez. Es el peor sitio para ir distraído el primer minuto.",
    lat: 52.3791,
    lng: 4.9003,
    distanceToNextKm: 0.9,
    bikeMinutesToNext: 5,
    legNote: "Vas a cruzar vías de tranvía en Prins Hendrikkade: crúzalas siempre en perpendicular, nunca en paralelo.",
  },
  {
    id: "dam",
    order: 2,
    name: "Dam Square",
    dayPart: "mañana",
    summary: "La plaza principal, con el Palacio Real y el Monumento Nacional.",
    whatToSee:
      "El Palacio Real (antiguo ayuntamiento), el Monumento Nacional y el ambiente de la plaza más viva del centro.",
    minutesHere: 15,
    tip: "Es zona peatonal saturada: baja del sillín y camina la bici los últimos metros hasta cruzar la plaza.",
    lat: 52.3731,
    lng: 4.8926,
    distanceToNextKm: 0.4,
    bikeMinutesToNext: 3,
    legNote: "Tramo corto y tranquilo por calles estrechas del centro histórico.",
  },
  {
    id: "begijnhof",
    order: 3,
    name: "Begijnhof",
    dayPart: "mañana",
    summary: "Un patio interior del siglo XIV que parece detenido en el tiempo.",
    whatToSee:
      "Las casas de fachada blanca alrededor del jardín, la capilla clandestina y la casa de madera más antigua de la ciudad.",
    minutesHere: 15,
    tip: "Se entra a pie por una puerta discreta en Spui: deja la bici bien candada fuera, dentro no se puede entrar con ella.",
    lat: 52.3701,
    lng: 4.891,
    distanceToNextKm: 0.5,
    bikeMinutesToNext: 3,
  },
  {
    id: "bloemenmarkt",
    order: 4,
    name: "Bloemenmarkt",
    dayPart: "mañana",
    summary: "El mercado flotante de flores sobre el Singel.",
    whatToSee: "Los puestos de tulipanes, bulbos y semillas instalados sobre barcazas fijas en el canal.",
    minutesHere: 10,
    tip: "Es una calle estrecha y muy transitada por turistas a pie: camina la bici en este tramo en vez de circular.",
    lat: 52.3673,
    lng: 4.8914,
    distanceToNextKm: 1.1,
    bikeMinutesToNext: 6,
    legNote: "Bordearás el Amstel: carril bici ancho y cómodo la mayor parte del trayecto.",
  },
  {
    id: "magere-brug",
    order: 5,
    name: "Magere Brug y el Amstel",
    dayPart: "mediodía",
    summary: "El puente levadizo más fotografiado de Ámsterdam.",
    whatToSee:
      "El puente de madera clásico sobre el río Amstel y las vistas abiertas del río, muy distintas a los canales estrechos del centro.",
    minutesHere: 10,
    tip: "El tablero de madera es resbaladizo con lluvia: cruza despacio y sin frenar en seco sobre las juntas metálicas.",
    lat: 52.3646,
    lng: 4.8997,
    distanceToNextKm: 1.4,
    bikeMinutesToNext: 7,
    legNote: "Tramo más largo del día: cruzarás zona de museos con más tráfico rodado.",
  },
  {
    id: "rijksmuseum",
    order: 6,
    name: "Rijksmuseum (exterior)",
    dayPart: "mediodía",
    summary: "El edificio y su famoso túnel-pasadizo para bicis.",
    whatToSee:
      "La fachada neogótica y, sobre todo, el pasaje que atraviesa el propio edificio: es carril bici real, no una foto.",
    minutesHere: 15,
    tip: "El túnel tiene prioridad marcada y suele haber cola: no adelantes dentro, es un espacio muy estrecho.",
    lat: 52.36,
    lng: 4.8852,
    distanceToNextKm: 0.3,
    bikeMinutesToNext: 2,
  },
  {
    id: "museumplein",
    order: 7,
    name: "Museumplein",
    dayPart: "mediodía",
    summary: "La gran explanada verde entre los museos, con el cartel de I amsterdam.",
    whatToSee: "La plaza abierta, el Van Gogh Museum y el Concertgebouw en los extremos.",
    minutesHere: 15,
    tip: "Aparca la bici en el parking de bicis subterráneo si vas a quedarte un rato: la plaza se llena de gente sentada en el suelo.",
    lat: 52.3579,
    lng: 4.8813,
    distanceToNextKm: 0.6,
    bikeMinutesToNext: 4,
  },
  {
    id: "vondelpark",
    order: 8,
    name: "Vondelpark",
    dayPart: "mediodía",
    summary: "El parque más grande y con más ambiente de la ciudad. Parada larga para comer algo y descansar.",
    whatToSee:
      "Los senderos junto al agua, los prados llenos de gente en verano y, si tienes suerte, algún concierto gratuito al aire libre.",
    minutesHere: 45,
    tip: "Dentro del parque hay carriles bici normales de doble sentido: respeta el lado derecho igual que en la calle.",
    lat: 52.3579,
    lng: 4.8686,
    distanceToNextKm: 1.9,
    bikeMinutesToNext: 9,
    legNote: "Vuelves hacia el centro por Leidsestraat o una paralela: es una de las calles con más tranvías, motos y turistas a la vez.",
  },
  {
    id: "negen-straatjes",
    order: 9,
    name: "Las Nueve Calles (Negen Straatjes)",
    dayPart: "tarde",
    summary: "Una cuadrícula de callejuelas con tiendas pequeñas y fachadas de canal clásicas.",
    whatToSee: "Las calles conectando Herengracht, Keizersgracht y Prinsengracht, con comercio independiente.",
    minutesHere: 40,
    tip: "Son calles muy estrechas y sin apenas carril bici propio: circula muy despacio y prioriza siempre al peatón.",
    lat: 52.3679,
    lng: 4.8836,
    distanceToNextKm: 0.6,
    bikeMinutesToNext: 4,
  },
  {
    id: "jordaan",
    order: 10,
    name: "Jordaan",
    dayPart: "tarde",
    summary: "El barrio con más carácter local: canales estrechos y casas de artesanos del siglo XVII.",
    whatToSee: "Egelantiersgracht y Bloemgracht, dos de los canales más fotogénicos y menos masificados.",
    minutesHere: 30,
    tip: "Es un barrio residencial: hay puertas y patios privados, respeta la vida diaria del vecindario al circular.",
    lat: 52.3745,
    lng: 4.8797,
    distanceToNextKm: 0.5,
    bikeMinutesToNext: 3,
  },
  {
    id: "westerkerk",
    order: 11,
    name: "Westerkerk y Casa de Ana Frank (exterior)",
    dayPart: "tarde",
    summary: "La torre más alta del centro y, justo al lado, la fachada de la Casa de Ana Frank.",
    whatToSee:
      "La torre Westertoren, coronada por la corona imperial de Ámsterdam, y la fachada del canal en Prinsengracht 263.",
    minutesHere: 20,
    optional: false,
    tip: "Suele haber cola larga en la puerta del museo: si no llevas entrada, admira la fachada desde la otra orilla del canal, hay menos gente.",
    lat: 52.3752,
    lng: 4.884,
    distanceToNextKm: 1.0,
    bikeMinutesToNext: 6,
    legNote: "Último tramo del día: vuelves bordeando los canales del centro hacia Centraal.",
  },
  {
    id: "canales-atardecer",
    order: 12,
    name: "Canales al atardecer",
    dayPart: "atardecer",
    summary: "Cierre del día pedaleando sin prisa junto al agua, con la luz baja sobre las fachadas.",
    whatToSee:
      "Herengracht y Singel iluminándose poco a poco: es el mejor momento del día para fotos, con mucha menos gente que por la mañana.",
    minutesHere: 30,
    tip: "Si vas a seguir después de que anochezca, es obligatorio llevar luces delantera y trasera encendidas.",
    lat: 52.3712,
    lng: 4.8952,
  },
];
